# This is a temporary file to get your site back online.
# It tells Netlify to ignore the functions folder for this deploy by commenting out the configuration.
# [functions]
#  directory = "netlify/functions/"
